/**
 * Books Dataset
 * Simulates a database of books using an array of objects.
 * Updated to use ISBNs for 100% reliable book covers from OpenLibrary.
 * Contains 25 famous books, with "Frankenstein" removed as requested.
 */

const generateCoverUrl = (isbn) => {
    // OpenLibrary API using ISBN is much more reliable than using title
    return `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;
};

const booksDatabase = [
    {
        id: "b1",
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Classic",
        rating: 4.8,
        price: 499,
        coverUrl: generateCoverUrl("9780743273565"),
        description: "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
        dateAdded: "2023-01-15",
        popularity: 95,
        reviews: ["A timeless masterpiece.", "Beautiful prose but unlikable characters."]
    },
    {
        id: "b2",
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        genre: "Classic",
        rating: 4.9,
        price: 550,
        coverUrl: generateCoverUrl("9780060935467"),
        description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
        dateAdded: "2023-02-10",
        popularity: 98,
        reviews: ["Essential reading for everyone.", "Deeply moving."]
    },
    {
        id: "b3",
        title: "Dune",
        author: "Frank Herbert",
        genre: "Sci-Fi",
        rating: 4.7,
        price: 899,
        coverUrl: generateCoverUrl("9780441172719"),
        description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.",
        dateAdded: "2023-03-05",
        popularity: 90,
        reviews: ["Worldbuilding at its finest.", "A bit dense at first but rewarding."]
    },
    {
        id: "b4",
        title: "1984",
        author: "George Orwell",
        genre: "Sci-Fi",
        rating: 4.6,
        price: 399,
        coverUrl: generateCoverUrl("9780451524935"),
        description: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real.",
        dateAdded: "2023-01-20",
        popularity: 92,
        reviews: ["Scarily prescient.", "A brilliant dystopia."]
    },
    {
        id: "b5",
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        rating: 4.8,
        price: 699,
        coverUrl: generateCoverUrl("9780547928227"),
        description: "A great modern classic and the prelude to The Lord of the Rings.",
        dateAdded: "2023-04-12",
        popularity: 88,
        reviews: ["An enchanting adventure.", "Perfect for all ages."]
    },
    {
        id: "b6",
        title: "Sapiens",
        author: "Yuval Noah Harari",
        genre: "Non-Fiction",
        rating: 4.7,
        price: 799,
        coverUrl: generateCoverUrl("9780062316097"),
        description: "From a renowned historian comes a groundbreaking narrative of humanity’s creation and evolution.",
        dateAdded: "2023-05-01",
        popularity: 85,
        reviews: ["Changed how I view the world.", "Fascinating insights."]
    },
    {
        id: "b7",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "Classic",
        rating: 4.9,
        price: 350,
        coverUrl: generateCoverUrl("9780141439518"),
        description: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language.",
        dateAdded: "2023-06-15",
        popularity: 96,
        reviews: ["The perfect romance.", "Austen's wit is unmatched."]
    },
    {
        id: "b8",
        title: "The Name of the Wind",
        author: "Patrick Rothfuss",
        genre: "Fantasy",
        rating: 4.5,
        price: 999,
        coverUrl: generateCoverUrl("9780756404741"),
        description: "Told in Kvothe's own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen.",
        dateAdded: "2023-07-22",
        popularity: 89,
        reviews: ["Beautifully written fantasy.", "Still waiting for book 3!"]
    },
    {
        id: "b9",
        title: "Atomic Habits",
        author: "James Clear",
        genre: "Non-Fiction",
        rating: 4.8,
        price: 650,
        coverUrl: generateCoverUrl("9780735211292"),
        description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day.",
        dateAdded: "2023-08-10",
        popularity: 99,
        reviews: ["Practical and actionable.", "A must-read for self-improvement."]
    },
    {
        id: "b10",
        title: "Neuromancer",
        author: "William Gibson",
        genre: "Sci-Fi",
        rating: 4.3,
        price: 599,
        coverUrl: generateCoverUrl("9780441569595"),
        description: "Before the Internet was in every house, before cypherpunks and hackers, there was Neuromancer, the cyberpunk masterpiece.",
        dateAdded: "2023-09-05",
        popularity: 80,
        reviews: ["Pioneering cyberpunk.", "Stylistically brilliant."]
    },
    {
        id: "b11",
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        genre: "Classic",
        rating: 4.0,
        price: 450,
        coverUrl: generateCoverUrl("9780316769488"),
        description: "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield.",
        dateAdded: "2023-10-12",
        popularity: 82,
        reviews: ["Captures teenage angst perfectly.", "Classic literature."]
    },
    {
        id: "b12",
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        genre: "Non-Fiction",
        rating: 4.6,
        price: 850,
        coverUrl: generateCoverUrl("9780374533557"),
        description: "The phenomenal New York Times Bestseller by Nobel Prize-winner Daniel Kahneman, explaining the two systems that drive the way we think.",
        dateAdded: "2023-11-20",
        popularity: 87,
        reviews: ["Mind-expanding.", "Dense but incredibly insightful."]
    },
    {
        id: "b13",
        title: "The Alchemist",
        author: "Paulo Coelho",
        genre: "Fiction",
        rating: 4.5,
        price: 399,
        coverUrl: generateCoverUrl("9780062315007"),
        description: "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.",
        dateAdded: "2023-12-01",
        popularity: 91,
        reviews: ["A beautiful fable.", "Highly inspirational."]
    },
    {
        id: "b14",
        title: "The Psychology of Money",
        author: "Morgan Housel",
        genre: "Non-Fiction",
        rating: 4.8,
        price: 499,
        coverUrl: generateCoverUrl("9780857197689"),
        description: "Timeless lessons on wealth, greed, and happiness doing well with money isn't necessarily about what you know.",
        dateAdded: "2023-12-05",
        popularity: 94,
        reviews: ["Great financial wisdom.", "Easy to read and understand."]
    },
    {
        id: "b15",
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        genre: "Fantasy",
        rating: 4.9,
        price: 799,
        coverUrl: generateCoverUrl("9780590353427"),
        description: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives. But his life is about to change forever.",
        dateAdded: "2023-12-10",
        popularity: 99,
        reviews: ["The beginning of an era.", "Magic in every page."]
    },
    {
        id: "b16",
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        rating: 4.9,
        price: 1299,
        coverUrl: generateCoverUrl("9780544003415"),
        description: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.",
        dateAdded: "2024-01-05",
        popularity: 97,
        reviews: ["The absolute pinnacle of fantasy.", "An epic journey."]
    },
    {
        id: "b17",
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        genre: "Fiction",
        rating: 4.7,
        price: 599,
        coverUrl: generateCoverUrl("9781594631931"),
        description: "The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father's servant.",
        dateAdded: "2024-01-10",
        popularity: 93,
        reviews: ["Heartbreaking and beautiful.", "A powerful story of redemption."]
    },
    {
        id: "b18",
        title: "Animal Farm",
        author: "George Orwell",
        genre: "Fiction",
        rating: 4.6,
        price: 299,
        coverUrl: generateCoverUrl("9780451526342"),
        description: "A brilliant political satire and allegorical tale about the corrupting influence of power.",
        dateAdded: "2024-01-15",
        popularity: 91,
        reviews: ["A brilliant allegory.", "Essential reading."]
    },
    {
        id: "b19",
        title: "Brave New World",
        author: "Aldous Huxley",
        genre: "Sci-Fi",
        rating: 4.5,
        price: 450,
        coverUrl: generateCoverUrl("9780060850524"),
        description: "A profound, prophetic, and horrifying vision of a 'utopian' future.",
        dateAdded: "2024-01-20",
        popularity: 88,
        reviews: ["Frighteningly accurate.", "A chilling dystopia."]
    },
    {
        id: "b20",
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        genre: "Classic",
        rating: 4.8,
        price: 650,
        coverUrl: generateCoverUrl("9780140449136"),
        description: "A psychological thriller about a young student who plots a murder, and the guilt that slowly consumes him.",
        dateAdded: "2024-01-25",
        popularity: 86,
        reviews: ["A deep dive into the human psyche.", "Incredible character study."]
    },
    {
        id: "b21",
        title: "The Da Vinci Code",
        author: "Dan Brown",
        genre: "Fiction",
        rating: 4.1,
        price: 550,
        coverUrl: generateCoverUrl("9780307474278"),
        description: "A gripping thriller involving symbology, secret societies, and a murder at the Louvre Museum.",
        dateAdded: "2024-02-01",
        popularity: 95,
        reviews: ["A total page-turner.", "Fast-paced and exciting."]
    },
    {
        id: "b22",
        title: "The Little Prince",
        author: "Antoine de Saint-Exupéry",
        genre: "Fiction",
        rating: 4.9,
        price: 399,
        coverUrl: generateCoverUrl("9780156012195"),
        description: "A poetic tale, with watercolor illustrations by the author, in which a pilot stranded in the desert meets a young prince fallen to Earth.",
        dateAdded: "2024-02-05",
        popularity: 98,
        reviews: ["Magical.", "Full of profound wisdom."]
    },
    {
        id: "b23",
        title: "The Fault in Our Stars",
        author: "John Green",
        genre: "Romance",
        rating: 4.8,
        price: 499,
        coverUrl: generateCoverUrl("9780142424179"),
        description: "A heart-wrenching romance between two teenagers who meet at a cancer support group.",
        dateAdded: "2024-02-10",
        popularity: 96,
        reviews: ["Absolutely beautiful.", "Bring tissues!"]
    },
    {
        id: "b26",
        title: "A Walk to Remember",
        author: "Nicholas Sparks",
        genre: "Romance",
        rating: 4.6,
        price: 350,
        coverUrl: generateCoverUrl("9780446608954"),
        description: "Every April, when the wind blows from the sea and mingles with the scent of lilacs, Landon Carter remembers his last year at Beaufort High.",
        dateAdded: "2024-03-01",
        popularity: 92,
        reviews: ["A beautiful love story.", "Very touching."]
    },
    {
        id: "b27",
        title: "The Notebook",
        author: "Nicholas Sparks",
        genre: "Romance",
        rating: 4.7,
        price: 399,
        coverUrl: generateCoverUrl("9780446605236"),
        description: "An old man reads to a woman with fading memory the story of two young lovers whose romance is threatened by their different social classes.",
        dateAdded: "2024-03-05",
        popularity: 98,
        reviews: ["A classic romance.", "Such a sweeping love story."]
    },
    {
        id: "b28",
        title: "Me Before You",
        author: "Jojo Moyes",
        genre: "Romance",
        rating: 4.6,
        price: 450,
        coverUrl: generateCoverUrl("9780670026609"),
        description: "A small-town girl is hired to care for a wealthy, successful man who has been paralyzed in an accident.",
        dateAdded: "2024-03-10",
        popularity: 95,
        reviews: ["A powerful and heartbreaking read.", "Wonderful character development."]
    },
    {
        id: "b24",
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        genre: "Classic",
        rating: 4.7,
        price: 499,
        coverUrl: generateCoverUrl("9780141441146"),
        description: "The story of an orphaned young woman who struggles to find her place in the world and falls in love with her mysterious employer.",
        dateAdded: "2024-02-15",
        popularity: 90,
        reviews: ["A brilliant gothic romance.", "A strong, independent heroine."]
    },
    {
        id: "b25",
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        genre: "Non-Fiction",
        rating: 4.5,
        price: 450,
        coverUrl: generateCoverUrl("9781612681139"),
        description: "What the rich teach their kids about money that the poor and middle class do not!",
        dateAdded: "2024-02-20",
        popularity: 92,
        reviews: ["Changed my financial mindset completely.", "Highly practical advice."]
    }
];

window.BooksDB = booksDatabase;
